name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Mini-XML sources
      uses: actions/checkout@v4
    - name: Update build environment
      run: sudo apt-get update --fix-missing -y
    - name: Install prerequisites
      run: sudo apt-get install -y cppcheck
    - name: Configure Mini-XML
      env:
        CC: /usr/bin/gcc
      run: ./configure --enable-debug --enable-maintainer --with-sanitizer
    - name: Build Mini-XML
      run: make
    - name: Test Mini-XML
      env:
        ASAN_OPTIONS: leak_check_at_exit=false
      run: make test
    - name: Run Clang Static Analyzer
      run: make CC=clang "GHA_ERROR=::error::" clang
    - name: Run cppcheck
      run: make "GHA_ERROR=::error::" cppcheck

  build-macos:

    runs-on: macos-latest

    steps:
    - name: Checkout Mini-XML sources
      uses: actions/checkout@v4
    - name: Configure Mini-XML
      run: ./configure --enable-debug --enable-maintainer --with-sanitizer
    - name: Build Mini-XML
      run: make
    - name: Test Mini-XML
      run: make test
    - name: Run Clang Static Analyzer
      run: make CC=clang "GHA_ERROR=::error::" clang

  build-windows:

    runs-on: windows-latest

    steps:
    - name: Checkout Mini-XML sources
      uses: actions/checkout@v4
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Build Mini-XML
      run: msbuild vcnet\mxml.sln
