EXESUFFIX=
OBJSUFFIX=.o
SLIBSUFFIX=.a
DYNLIBSUFFIX=.so

CC=clang -Wall -pedantic -ansi -std=c99 -lm
CCLIB=clang -Wall -fPIC -pedantic -ansi -std=c99 -lm
CP=cp
MKDIR=mkdir -p
ARCMD=ar rcs
SHAREDCC=clang -Wall -shared
MAKE=make
MKSTAGEARCHIVE=tar -czf packages/libstlio-amd64-linux.tar.gz -C stage .
RMDIR=rm -rf
RMFILR=rm
